"""Host nginx generation/validation."""

from __future__ import annotations

import json
import os
import re
import sys
import tempfile
from pathlib import Path

from sbfleet import registry as reg
from sbfleet.cli import EXIT_FAILURE, EXIT_OK, EXIT_PREREQUISITE, EXIT_SAFETY
from sbfleet.process import run

SERVER_RE = re.compile(
    r"^[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?"
    r"(?:\.[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?)*$"
)


def render_nginx(meta: dict) -> str:
    domain = meta.get("domain")
    port = int(meta["ports"]["gateway"])
    slug = meta["slug"]
    if not domain:
        return (
            f"# TEMPLATE ONLY — project {slug} has no domain; ready_to_install:false\n"
            f"# Replace DOMAIN and certificate paths before install.\n"
            f"# upstream gateway 127.0.0.1:{port}\n"
            f"upstream sbfleet_{slug} {{\n"
            f"    server 127.0.0.1:{port};\n"
            f"    keepalive 32;\n"
            f"}}\n"
            f"# server {{ ... server_name DOMAIN; ... proxy_pass http://sbfleet_{slug}; }}\n"
        )
    if not SERVER_RE.fullmatch(domain) or any(ch in domain for ch in "{};$\n\r"):
        raise ValueError("invalid domain")
    return f"""# generated by sbfleet for {slug} — do not put secrets here
# ready_to_install:false until operator supplies real certificates
map $http_upgrade $connection_upgrade {{
    default upgrade;
    '' close;
}}
upstream sbfleet_{slug} {{
    server 127.0.0.1:{port};
    keepalive 32;
}}
server {{
    listen 127.0.0.1:8443 ssl;
    server_name {domain};
    # ssl_certificate /path/to/fullchain.pem;
    # ssl_certificate_key /path/to/privkey.pem;
    client_max_body_size 50m;
    location / {{
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_pass http://sbfleet_{slug};
    }}
}}
server {{
    listen 127.0.0.1:8080;
    server_name {domain};
    return 301 https://$host$request_uri;
}}
"""


def render_fixture_http_only(meta: dict, *, listen_port: int = 18080) -> str:
    """HTTP-only fixture config for disposable nginx container (no host /etc)."""
    domain = meta.get("domain") or f"{meta['slug']}.sbfleet.test"
    port = int(meta["ports"]["gateway"])
    slug = meta["slug"]
    if not SERVER_RE.fullmatch(domain):
        raise ValueError("invalid domain")
    return f"""# sbfleet G9 fixture — host nginx untouched
worker_processes 1;
error_log /tmp/nginx-error.log;
pid /tmp/nginx.pid;
events {{ worker_connections 64; }}
http {{
    access_log /tmp/nginx-access.log;
    map $http_upgrade $connection_upgrade {{
        default upgrade;
        '' close;
    }}
    upstream sbfleet_{slug} {{
        server host.docker.internal:{port};
        keepalive 16;
    }}
    server {{
        listen 127.0.0.1:{listen_port};
        server_name {domain};
        client_max_body_size 50m;
        location / {{
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_pass http://sbfleet_{slug};
        }}
        # Explicitly do NOT proxy database ports
        location /db {{
            return 404;
        }}
    }}
}}
"""


def nginx_cmd(root: Path, args) -> int:  # noqa: ANN001
    if args.action == "install":
        print(
            "INSTRUCTIONS_ONLY — Manual install only:\n"
            "  1) copy generated/nginx.conf to /etc/nginx/sites-available/sbfleet-<slug>\n"
            "  2) ln -s into sites-enabled\n"
            "  3) nginx -t && systemctl reload nginx\n"
            "sbfleet never runs sudo or reloads the host."
        )
        return EXIT_OK
    if not args.project:
        print("error: project required", file=sys.stderr)
        return 2
    try:
        meta = reg.read_project(root, args.project)
        text = render_nginx(meta)
    except (reg.RegistryError, ValueError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return EXIT_SAFETY
    out = reg.project_dir(root, args.project) / "generated" / "nginx.conf"
    if args.action == "generate":
        out.parent.mkdir(parents=True, exist_ok=True)
        if out.exists() and out.read_text(encoding="utf-8") != text:
            print(
                "error: nginx.conf exists with different content; refuse overwrite "
                "(delete or replace manually after review)",
                file=sys.stderr,
            )
            return EXIT_SAFETY
        out.write_text(text, encoding="utf-8")
        if args.json:
            print(
                json.dumps(
                    {
                        "format_version": 1,
                        "ok": True,
                        "command": "nginx",
                        "data": {
                            "path": str(out),
                            "template": not bool(meta.get("domain")),
                            "ready_to_install": False,
                        },
                        "warnings": [],
                        "errors": [],
                    }
                )
            )
        else:
            print(f"wrote {out}")
        return EXIT_OK
    if args.action == "validate":
        if not out.exists():
            print("error: generate first", file=sys.stderr)
            return EXIT_FAILURE
        if not meta.get("domain"):
            print("error: template-only config is not valid for install", file=sys.stderr)
            return EXIT_FAILURE
        if not __import__("shutil").which("nginx"):
            print("error: nginx binary missing", file=sys.stderr)
            return EXIT_PREREQUISITE
        with tempfile.TemporaryDirectory(prefix="sbfleet-nginx-") as td:
            prefix = Path(td)
            for d in ("logs", "tmp", "client_body_temp", "proxy_temp"):
                (prefix / d).mkdir()
            # Strip listen ssl without certs for syntax-only host nginx -t:
            # use a syntax-check wrapper that includes upstream+server with stub ssl off
            site = out.read_text(encoding="utf-8")
            # For -t without certs, comment ssl listen lines
            site_check = "\n".join(
                ("# " + line) if "listen" in line and "ssl" in line else line
                for line in site.splitlines()
            )
            site_path = prefix / "site.conf"
            site_path.write_text(site_check, encoding="utf-8")
            main = prefix / "nginx.conf"
            main.write_text(
                "worker_processes 1;\n"
                f"error_log {prefix / 'logs' / 'error.log'};\n"
                f"pid {prefix / 'nginx.pid'};\n"
                "events { worker_connections 64; }\n"
                "http {\n"
                f"  access_log {prefix / 'logs' / 'access.log'};\n"
                f"  include {site_path};\n"
                "}\n",
                encoding="utf-8",
            )
            result = run(
                ["nginx", "-t", "-c", str(main), "-p", str(prefix)],
                env={"PATH": os.environ.get("PATH", "/usr/bin:/bin")},
                check=False,
            )
            if not result.ok:
                print(result.stderr or result.stdout, file=sys.stderr)
                return EXIT_FAILURE
            print(
                "nginx -t ok on SSL-listen-stripped syntax-check text "
                "(private prefix; host /etc/nginx untouched; "
                "not proof the install-ready TLS artifact is valid)",
            )
            return EXIT_OK
    return 2
